#!/bin/bash

pip install ecmwflibs
pip install earthkit@git+https://github.com/ecmwf/earthkit@freeze-for-ga

# Install EK packages
pip install earthkit-data@git+https://github.com/ecmwf/earthkit-data@develop --upgrade
# conda install -y -c conda-forge earthkit-data 

#pip install earthkit-maps --upgrade
pip install earthkit-maps>=0.0.8 --upgrade
pip install earthkit-climate>=0.0.9 --upgrade

mkdir test_data/
